// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	v1 "promise/api/v1"
	"promise/internal/model"
)

type IEvent interface {
	AddEvent(ctx context.Context, req *v1.EventAddReq) (err error)
	AddEventByChannel(ctx context.Context, req *v1.EventBaseReq) (err error)
	GetWeekEventListFromDb(ctx context.Context) (value interface{}, err error)
	GetWeekEventListFromCache(ctx context.Context) (list []*model.EventListItem, err error)
}

var localEvent IEvent

func Event() IEvent {
	if localEvent == nil {
		panic("implement not found for interface IEvent, forgot register?")
	}
	return localEvent
}

func RegisterEvent(i IEvent) {
	localEvent = i
}
