// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"promise/internal/dao/internal"
)

// internalCarinfoDao is internal type for wrapping internal DAO implements.
type internalCarinfoDao = *internal.CarinfoDao

// carinfoDao is the data access object for table carinfo.
// You can define custom methods on it to extend its functionality as you wish.
type carinfoDao struct {
	internalCarinfoDao
}

var (
	// Carinfo is globally public accessible object for table carinfo operations.
	Carinfo = carinfoDao{
		internal.NewCarinfoDao(),
	}
)

// Fill with you ideas below.
