// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"promise/internal/dao/internal"
)

// internalEventsmallDao is internal type for wrapping internal DAO implements.
type internalEventsmallDao = *internal.EventsmallDao

// eventsmallDao is the data access object for table eventsmall.
// You can define custom methods on it to extend its functionality as you wish.
type eventsmallDao struct {
	internalEventsmallDao
}

var (
	// Eventsmall is globally public accessible object for table eventsmall operations.
	Eventsmall = eventsmallDao{
		internal.NewEventsmallDao(),
	}
)

// Fill with you ideas below.
