// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Carinfo is the golang structure of table carinfo for DAO operations like Where/Data.
type Carinfo struct {
	g.Meta             `orm:"table:carinfo, do:true"`
	VehicleNumber      interface{} // 车辆编号
	VehicleModle       interface{} // 车辆型号
	VehicleFrameNumber interface{} // 车架号
	VehicleUsage       interface{} // 车辆用途
	VehicleRegion      interface{} // 所属地区
	Version            interface{} // 大版本号
	Status             interface{} // 车辆状态
}
