// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"promise/internal/dao/internal"
)

// internalEventmiddleDao is internal type for wrapping internal DAO implements.
type internalEventmiddleDao = *internal.EventmiddleDao

// eventmiddleDao is the data access object for table eventmiddle.
// You can define custom methods on it to extend its functionality as you wish.
type eventmiddleDao struct {
	internalEventmiddleDao
}

var (
	// Eventmiddle is globally public accessible object for table eventmiddle operations.
	Eventmiddle = eventmiddleDao{
		internal.NewEventmiddleDao(),
	}
)

// Fill with you ideas below.
