// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Carinfo is the golang structure for table carinfo.
type Carinfo struct {
	VehicleNumber string `json:"vehicleNumber" description:"车辆编号"`
	VehicleModel  string `json:"vehicleModel"  description:"车辆型号"`
	SliceUrl      string `json:"sliceUrl"      description:"切片存储地址"`
	SliceName     string `json:"sliceName"     description:"切片名称"`
	SliceSize     int    `json:"sliceSize"     description:"切片大小"`
	SliceMd5      string `json:"sliceMd5"      description:"切片md5值"`
	EventId       int    `json:"eventId"       description:"事件id"`
	Vin           string `json:"vin"           description:"车架号"`
	VehicleUse    string `json:"vehicleUse"    description:"车辆用途"`
	VehicleArea   string `json:"vehicleArea"   description:"所属地区"`
}
