// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Carinfo is the golang structure for table carinfo.
type Carinfo struct {
	VehicleNumber      string `json:"vehicleNumber"      description:"车辆编号"`
	VehicleModel       string `json:"vehicleModel"       description:"车辆型号"`
	VehicleFrameNumber string `json:"vehicleFrameNumber" description:"车架号"`
	VehicleUsage       string `json:"vehicleUsage"       description:"车辆用途"`
	VehicleRegion      string `json:"vehicleRegion"      description:"所属地区"`
	Version            string `json:"version"            description:"大版本号"`
	Status             string `json:"status"             description:"车辆状态"`
}
