// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Eventmiddle is the golang structure for table eventmiddle.
type Eventmiddle struct {
	EventId          int         `json:"eventId"          description:"事件id"`
	EventTime        *gtime.Time `json:"eventTime"        description:"事件发生日期/时间"`
	EventType        string      `json:"eventType"        description:"事件类型"`
	EventDescription string      `json:"eventDescription" description:"事件描述"`
	StartTime        *gtime.Time `json:"startTime"        description:"数据开始时间"`
	Duration         int         `json:"duration"         description:"切片数据的持续时间(s)"`
	TriggerType      string      `json:"triggerType"      description:"事件触发方式"`
	SliceUrl         string      `json:"sliceUrl"         description:"slice数据地址"`
	VehicleNumber    string      `json:"vehicleNumber"    description:"车辆编号"`
	VehicleModel     string      `json:"vehicleModel"     description:"车辆型号"`
}
