server:
  address:     ":39123"
  serverRoot:          "resource/public"
  dumpRouterMap:       true
  routeOverWrite:      true
  accessLogEnabled:    false
  accessLogPattern:    "access-{Ymd}.log"
  sessionPath:         "temp/sessions"    # Session文件存储目录
  openapiPath:         "/api.json"
  swaggerPath:         "/swagger"
  websocketserver:
    address:    ":39124"



# 数据库连接配置
database:
  logger:
    path:    "logs/sql"
    level:   "all"
    stdout:  true
    ctxKeys: ["RequestId"]

  default:
    link:   "mysql:root:admin@tcp(118.25.144.84:6607)/dataloop"
    debug:  true
    maxIdle: 10 #连接池最大闲置的连接数
    maxOpen: 10 #连接池最大打开的连接数
    maxLifetime: 30 #(单位秒)连接对象可重复使用的时间长度

# Logger configurations.
logger:
  path:    "logs/default"
  level:   "all"
  stdout:  true
  ctxKeys: ["RequestId"]

# 模板引擎配置
viewer:
  indexLayout:     "index/index.html"
  adminHomeLayout: "admin/home.html"
  adminLayout:     "admin/index.html"





