// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "promise/internal/logic/carInfo"
	_ "promise/internal/logic/event"
)
