// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// User is the golang structure for table user.
type User struct {
	Id       string `json:"id"       description:"用户唯一标识"`
	Username string `json:"username" description:"用户姓名"`
	Mobile   string `json:"mobile"   description:"中国手机不带国家代码，国际手机号格式为：国家代码-手机号"`
	Picture  string `json:"picture"  description:"用户头像 url"`
	Email    string `json:"email"    description:"用户邮箱"`
}
