// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Carinfo is the golang structure of table carinfo for DAO operations like Where/Data.
type Carinfo struct {
	g.Meta        `orm:"table:carinfo, do:true"`
	VehicleNumber interface{} // 车辆编号
	VehicleModel  interface{} // 车辆型号
	SliceUrl      interface{} // 切片存储地址
	SliceName     interface{} // 切片名称
	SliceSize     interface{} // 切片大小
	SliceMd5      interface{} // 切片md5值
	EventId       interface{} // 事件id
	Vin           interface{} // 车架号
	VehicleUse    interface{} // 车辆用途
	VehicleArea   interface{} // 所属地区
}
