// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Eventsmall is the golang structure of table eventsmall for DAO operations like Where/Data.
type Eventsmall struct {
	g.Meta           `orm:"table:eventsmall, do:true"`
	EventId          interface{} // 事件id
	EventTime        *gtime.Time // 事件发生日期/时间
	EventType        interface{} // 事件类型
	EventDescription interface{} // 事件描述
	StartTime        *gtime.Time // 切片数据开始时间
	Duration         interface{} // 切片数据的持续时间(s)
	TriggerType      interface{} // 事件触发方式
	SliceUrl         interface{} // slice数据地址
	VehicleNumber    interface{} // 车辆编号
	VehicleModel     interface{} // 车辆型号
}
